sudo: required
services:
  - docker 

before_install:
  - docker build -t mmeenapriya/multi-docker -f ./client/Dockerfile.dev ./client


script:
  - docker run mmeenapriya/multi-docker npm test -- --coverage

after_success:
  - docker build -t mmeenapriya/multi-client ./client
  - docker build -t mmeenapriya/multi-nginx ./nginx 
  - docker build -t mmeenapriya/multi-server ./server
  - docker build -t mmeenapriya/multi-worker ./worker 
  # Log in to the docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub 
  - docker push mmeenapriya/multi-client 
  - docker push mmeenapriya/multi-nginx 
  - docker push mmeenapriya/multi-server 
  - docker push mmeenapriya/multi-worker 

deploy:
  provider: elasticbeanstalk 
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-343541161952
  bucket_patj: docker-multi
  on: 
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_acces_key :
    secure: $AWS_SECRET_KEY
